---
apiVersion: v1
kind: Service
metadata:
  name: load-generator
  namespace: ecommerce-demo
  labels:
    app: load-generator
spec:
  selector:
    app: load-generator
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: ecommerce-demo
  labels:
    app: product-catalog
spec:
  selector:
    app: product-catalog
  ports:
    - port: 8014
      targetPort: 8014
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: ecommerce-demo
  labels:
    app: checkout
spec:
  selector:
    app: checkout
  ports:
    - port: 8016
      targetPort: 8016
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: ecommerce-demo
  labels:
    app: cart
spec:
  selector:
    app: cart
  ports:
    - port: 8013
      targetPort: 8013
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: ecommerce-demo
  labels:
    app: recommendation
spec:
  selector:
    app: recommendation
  ports:
    - port: 8011
      targetPort: 8011
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: currency
  namespace: ecommerce-demo
  labels:
    app: currency
spec:
  selector:
    app: currency
  ports:
    - port: 8018
      targetPort: 8018
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: ecommerce-demo
  labels:
    app: shipping
spec:
  selector:
    app: shipping
  ports:
    - port: 8019
      targetPort: 8019
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ad-service
  namespace: ecommerce-demo
  labels:
    app: ad-service
spec:
  selector:
    app: ad-service
  ports:
    - port: 8017
      targetPort: 8017
      protocol: TCP
      name: http
  type: ClusterIP
